module.exports = {
  docs: [
    {
      type: 'doc',
      label: '🦖 Intro',
      id: 'index',
    },
    {
      type: 'category',
      label: '🧑‍🚀 Overview',
      collapsed: false,
      items: [
        'getting-started/create-your-first-test',
        'getting-started/what-is-crusher',
        'getting-started/features',
        'development/architecture',

      ],
    },

    {
      type: 'category',
      label: '💡 Guides',
      collapsed: true,
      items: ['guides/setting-up-services'],
    },
    {
      type: 'category',
      label: '⚽ Integration',
      collapsed: true,
      items: ['setting-up/manage-alerts', 'setting-up/github', 'integrations/with-vercel', 'integrations/with-ci-cd'],
    },
    {
      type: 'category',
      label: '🏄‍♂️ Code',
      collapsed: true,
      items: ['advanced/custom-code-usecases-1', 'advanced/custom-code-usecases', 'advanced/making-network-requests', 'advanced/writing-custom-selectors'],
    },
    {
      type: 'category',
      label: 'Misc',
      collapsed: true,
      items: ['advanced/faq'],
    },
    {
      type: 'category',
      label: '🧱 Contribute',
      collapsed: true,
      items: [
        'development/contributing',
        'development/docker-deploy-locally',
        'development/setting-up-development-env',
        'getting-started/how-crusher-works',
      ],
    },
  ],


  cli: [
    {
      type: 'category',
      label: 'CLI Documentation',
      collapsed: true,
      items: ['cli', 'cli/using-cli-in-project', 'cli/custom-host', 'cli/global-option', 'cli/project-options'],
    },
    {
      type: 'category',
      label: 'Command Reference',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'cli/commands', // Generate section automatically based on files
        },
      ],
    },
  ],
};
