module.exports = {
  docs: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: true,
      items: ['index','intro/getting-started-crusher', 'intro/cli', 'intro/components'],
    },
    {
      type: 'category',
      label: 'SDK',
      collapsed: true,
      items: [
        'sdk/use-cases',
        'sdk/reference',
        {
          type: 'category',
          label: 'Guides',
          collapsed: true,
          items: [
            "sdk/guides/writing-custom-code",
            "sdk/guides/add-assertions"
          ]
        },
      ],
    },
  ],

  cli: [
    {
      type: 'category',
      label: 'CLI Documentation',
      collapsed: true,
      items: [
        'cli',
        'cli/configuration',
        'cli/global-option',
        'cli/project-options',
      ],
    },
    {
      type: 'category',
      label: 'Command Reference',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'cli/commands', // Generate section automatically based on files
        },
      ],
    },
  ],
};
